### ISSUE TITLE
Missing license & credit

### ISSUE THREAD

**Issue by Gadgetoid** [oneearedrabbit/badger-system-ii#1]
This repository should be marked MIT licensed and/or include a copy of https://github.com/pimoroni/pimoroni-pico/blob/main/LICENSE with the relevant derived files.

The STL case files (if they are the ones I think they are) are CC NC BY, I think an accreditation link to https://www.thingiverse.com/thing:5320100 would suffice.

I looooove that Mac style UI. Very, very slick.

**Comment by oneearedrabbit** [comment]
Cool beans! I'll scan for the derivatives and/or inspiration sources to explicitly mention their licenses and/or link source files whenever applicable. I'll try to release everything else under WTFPL or similar license. Give me a little time to clean everything up. In the spirit of a hack project, I chaotically put everything that I have in the repo.

I doubt I will be making any significant changes at this point to the app to split up Pimoroni examples from custom code. I'll take the path of least resistance, and may end up with MIT/CC licenses in the end.

**Comment by oneearedrabbit** [comment]
In the meantime, I referenced this issue in README file.

**Comment by oneearedrabbit** [comment]
I'll use this issue to track references/licenses. I will incorporate them into the repository once I am confident that I captured everything.

Inspiration sources for the case:
- https://kaenner.de/badger2040 (CC4)
- https://www.thingiverse.com/thing:5320100/files (CC4)

I ended up using an OpenSCAD blueprint by usedbytes to get measurements of the device. Reconstructed/synthesized a new case in Fusion360. Noticeable changes:
- A different battery holder to simplify the assembly to some extend
- Two coin cells vs three
- Added hidden buttons inspired by Känner's design 
- Back panel is inspired by Känner's design too, I like that connectors are accessible
- Battery toggle button
- Any mistakes are exclusively mine

Source code:
- To a large extend based on pimoroni Badger2040 OS example: https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/badger2040 (MIT)
- Font & rendering: custom code, but it is not worth extracting it to a standalone app/library. Let's stick with MIT for simplicity too.

Assets:
- Font: 16bfZX https://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=246 (Public domain)
- Clippy: hand-drawn, I think the character is trademarked by Microsoft though.
- Other assets: hand-drawn

@Gadgetoid Does it look like a complete list to you?

**Comment by oneearedrabbit** [comment]
I added this list to README. https://github.com/oneearedrabbit/badger-system-ii#license--acknowledgements. If you think something is not clear or missing, feel free to reopen.

I appreciate you bringing this up, and thanks for Badger OS -- sweet, sweet examples to get started with Badger2040!

**Comment by Gadgetoid** [comment]
To be honest I don't actually mind what you do with my/our code, I was mostly interested in the origin of the case since us Pi community folks are a close-knit bunch and we talk :laughing:

Thank you for putting in the effort to add references- it's all really useful detail that helps people get started with their own, similar, projects.

Drop me an email if you'd like a Badger 2040 W to play with!
