### ISSUE TITLE
error with more than 1 qr code txt file

### ISSUE THREAD

**Issue by kfarr** [oneearedrabbit/badger-system-ii#3]
On this line
https://github.com/oneearedrabbit/badger-system-ii/blob/9988bb0b9612d327eecd6a83e3c5495f4a82b0e6/src/qr_app.py#L111

dissplay should be display

**Comment by oneearedrabbit** [comment]
@kfarr Good catch! I was considering adding a multi-QR support, but eventually dropped this feature -- needs some UX love. Code is there, but as you can see I never tested it. Do you want to take it as a quick win, honors are yours and open a PR? It is okay, if not -- I can edit files later today/tomorrow.

**Comment by kfarr** [comment]
Sure just made a super simple PR now: https://github.com/oneearedrabbit/badger-system-ii/pull/4

Once I fixed this the qr app works as expected, you can use up/down arrows to switch as expected. I suppose someone could go all out and make the old school scrollbar (visible in "special") functional instead of the boxes

**Comment by oneearedrabbit** [comment]
Thank you! Merged!
