### ISSUE TITLE
top case is not oriented properly

### ISSUE THREAD

**Issue by tachijuan** [oneearedrabbit/badger-system-ii#5]
Nice job on everything, but I think the top case is not the right version. The USB-C and the edge connector holes are on the wrong side of the case. See attached picture of my print of the case. Notice the USB port on the case is on the right of the image and the USB port is on the left on the badger. Notice also the correct orientation of the lanyard hole. The preview of the STL on github shows the same orientation as my print so it doesn't appear to be something strange with my slicer. 

![IMG_7985](https://user-images.githubusercontent.com/167389/223271629-1cb9a5e9-38fd-44f7-a82c-a1775d37c4d8.jpeg)

**Comment by oneearedrabbit** [comment]
Interesting. I might have mirrored it in Slic3r, but accidentally uploaded a wrong file? I don't remember, but better to fix it. Thanks for opening a ticket and sorry for the trouble! Which tool would you recommend to transform the STL file (I can do this in Fusion, but it feels such an easy task!) or perhaps you could open a PR?

**Comment by tachijuan** [comment]
You know - I didn't even think of mirroring it in Prusa Slicer. Printing now. If it prints properly, I'll do a PR with the correct STL

**Comment by oneearedrabbit** [comment]
Thanks, please let me know if it works, exciting! I can dig up the right file a little later to confirm. Sorry that I messed it up, I'll update the README in the meantime.

**Comment by tachijuan** [comment]
Printed and worked correctly. PR created.

**Comment by oneearedrabbit** [comment]
Thank you, merged!

**Comment by kfarr** [comment]
I encountered the same issue, thank you for flagging!
